name: 'Set Github Variable'
author: Open Foxes
description: 'Update Github variables from within actions'

inputs:
    name:
        description: Variable name
        required: true

    value:
        description: Variable value
        required: true

    repository:
        description: Repository name, with format "<organization>/<repository>" i.e "OpenFoxes/set-github-variable"
        default: ${{ github.repository }}
        required: true

    token:
        description: Repository access token (Personal Access Token or Organization Token)
        required: true

    org:
        description: Only in case of Org-scope variable, specifies if the variable belongs to an organization
        required: false

    visibility:
        description: Only in case of Org-scope variable, specifies the access level 'all', 'private', or 'selected'
        required: false

    selectedRepositoryIds:
        description: Only in case of Org-scope variable and visibility equals selected, it's an array of repository ids where to update the variable
        required: false

outputs:
    code:
        description: Status code

    data:
        description: Response data

runs:
    using: 'node12'
    main: 'src/index.js'
