name: Create Release

on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Version (SemVer)'
                required: true
                default: 0.0.0

jobs:
    set-version:
        name: Update version in documentation
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  token: ${{ secrets.BOT_TOKEN }}

            - name: Update package version
              run: yarn version --no-git-tag-version --new-version ${{  github.ref_name }}

            - name: Update README
              run: yarn run generate-readme ${{  github.ref_name }}

            - name: Add corresponding commit
              run: |
                  git config --global user.name 'OpenFoxes Maintenance Bot'
                  git config --global user.email 'openfoxes@bono-fox.de'
                  git init
                  git add .
                  git commit -m "🔖 Release ${{  github.ref_name }}" -m "- Updated documentation"
                  git tag v${{  github.ref_name }}
                  git push -u origin HEAD:main --tags

    test:
        name: Run tests
        runs-on: ubuntu-latest
        needs: [set-version]
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 20

            - run: yarn

            - run: yarn lint

    create-github-release:
        name: 'Create GitHub release'
        runs-on: ubuntu-latest
        needs: [test]
        steps:
            - uses: actions/checkout@v4

            - uses: softprops/action-gh-release@v2
              with:
                  token: ${{ secrets.ACTION_TOKEN }}
                  name: Version ${{  github.ref_name }}
                  tag_name: v${{  github.ref_name }}
